### ISSUE TITLE
# sign is causing syntax highlighting errors

### ISSUE THREAD

**Issue by koreys** [atom/language-html#104]
"A" tags that have a href="#content" or any other #section are causing syntax highlighting errors. See attached image:

<img width="999" alt="screenshot 2016-01-25 14 35 13" src="https://cloud.githubusercontent.com/assets/3834710/12562088/4d3d866e-c371-11e5-9f32-68f174a49d4a.png">

**Comment by spitzgoby** [comment]
I'm having the same issue. As best as I can tell it's an issue with pattern matching in [line 358](https://github.com/atom/language-html/blob/master/grammars/html.cson#L358) of `html.cson`

**Comment by PatrickJoannisse** [comment]
I have a similar issue with a single quote in the paragraph text. Might be related.

https://github.com/atom/language-html/issues/144

**Comment by 50Wliu** [comment]
I cannot reproduce using the following example on language-html@0.47.7 (bundled with Atom 1.21.0):
![hash-in-strings](https://user-images.githubusercontent.com/2766036/30523738-f1ab08e4-9be6-11e7-9dc6-26e8a60a091d.png)
