### ISSUE TITLE
Html Tab

### ISSUE THREAD

**Issue by jel111** [atom/language-html#106]
Just doesn't work. I tried reinstall but I type html hit tab and it just gives me emmet's version.

**Comment by lee-dohm** [comment]
Emmet interferes with Atom's built-in keymaps. This is a [long-standing issue](https://discuss.atom.io/t/having-weird-problems-do-you-have-emmet-installed/18805). Can you reproduce the issue in Safe Mode?

To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/language-html/issues/106#issuecomment-178904390. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
