### ISSUE TITLE
Clean your snippets

### ISSUE THREAD

**Issue by corysimmons** [atom/language-html#107]
https://github.com/atom/atom/issues/10688

`input[tab]` expands to `<input type="button" name="name" value="">`

Who wants that? Is there anyone who actually wants `input` to expand to `<input type="button" name="name" value="">`?

It's like this with a bunch of snippets.

Remove all the cruft from these. `input[tab]` should expand to `<input>`..

**Comment by 50Wliu** [comment]
I'm not sure if you're aware of this but if you keep tabbing you can change the type, name, and value.  Would it be acceptable if a second tab would highlight everything after `input` (ie the `type="button" name=...`) so that you could delete it easily?

**Comment by mnquintana** [comment]
You can also add your own custom snippets, and override the default one for `input`: https://atom.io/docs/latest/using-atom-snippets#creating-your-own-snippets

**Comment by lee-dohm** [comment]
The snippets included in all of our language packages are ones that the Atom team or other members of the community have found useful and are found in other common editors. There are options available to you if the built-in snippets aren't to your liking:

* Disable the [snippets package](https://github.com/atom/snippets) completely
* [Override the built-in snippets](https://atom.io/docs/latest/using-atom-snippets) with snippets of your own in your `snippets.cson`

Thanks for the feedback. I have brought it up to the team and we've decided to keep the snippets that are already there.

**Comment by corysimmons** [comment]
@lee-dohm I don't think your team is being genuine when they say `input` should expand to `<input type="button" name="name" value="">`.

Why not add `required`? People usually want inputs filled out. Or `pattern`? I typically want to make sure a field only accepts certain characters in input. Oh, and maybe `min` and `max` just in case it's a number? I can always just tab/delete anything I don't use every single time I make an input field. :smiley_cat: 

In a decade+ of web development, you know how many times I've used `<input type="button" name="" value="">`? Zero.

You know how many times I've wanted to expand `input` to `<input type="text">`? More than zero.

"it's the way everyone else does it" will never be a valid justification for anything...

How did you have a real conversation about the pro's and con's of your snippets (that I'm assuming you blindly copied from other libraries?) with your team in 17 minutes (assuming you read my issue, organized this conference, and held this conversation the second I submitted my issue)?

Can you reopen this for community discussion since Atom is an open source project? I'm genuinely curious if I'm completely missing the merits of `<input type="button" name="name" value="">` and similar junk.

**Comment by demhydraz** [comment]
Hi. I'm a communiy member. I'm discussing this. Does that count as community discussion?

Well, it does now.

@corysimmons if you were to actually read the docs and the [source](https://github.com/atom/language-html/blob/master/snippets/language-html.cson#L172) of the snippet in question, you'd discover that the `button` text is automatically selected, and if you were to press tab, it'd select the `name` text, and if you were to hit tab again, it'd place your cursor in between the quotation marks of the value field.

One last tab, and you're placed after the closing `>` of the tag.

Even though this snippet is, in my opinion, clearly _useful_, you may find that it's distracting. In that case, you can either:

- Append the following text into your `snippets.cson`, which will make `input[tab]` expand into `<input|>`, where | is your cursor
```coffee-script
'.source.html':
  'Input':
    prefix: 'input'
    body: '<input$1>'
```
- Unbind <kbd>Tab</kbd> or bind it to something more useful, by appending this cson into your `keymap.cson`

```coffee-script
'atom-text-editor:not(mini)':
  'tab': 'unset!' # or 'tab': 'autocomplete-plus:activate', which imo would make for a better default
```


All in all, if you're not happy with the current snippet behaviour, you can replace it with something better suited to your tastes or disable it altogether. I see no reason for overriding the default, seeing as you're the first_[citation needed]_ to complain about this.

**Comment by 50Wliu** [comment]
> seeing as you're the first [citation needed] to complain about this.

I just want to say that there always has to be someone to start the complaint - you shouldn't be going against @corysimmons simply because he was the first person to speak up.  Your tone (as well as @corysimmons') also appear to be very confrontational, and we'll get a better conversation going if everyone was more cordial to each other.

**Comment by corysimmons** [comment]
> Your tone (as well as @corysimmons') also appear to be very confrontational, and we'll get a better conversation going if everyone was more cordial to each other.

I'm sorry. It's frustrating that everyone is screwing up default snippets so badly and standing by it... Emmet does this crap too with `<textarea name="" id="" cols="30" rows="10"></textarea>`, etc.

My options are:

1) Continue to deal with this annoyance that I've already been dealing with for several years.
2) Make my own snippets and ignore the underlying problem that I'm sure many other people have been dealing with for years.
3) Put the stuff I want to build on hold and make a text expander (with plugins to major editors) from the ground up.

The problem is clear but people don't want to fix it because modernizing every snippet would be tedious and boring.

Actually it takes much less time to write a huge project from scratch than to get some maintainers to do the right thing.

@demhydraz Thanks for teaching me how to use snippets. 😂:100:
