### ISSUE TITLE
Bug in "type" attribute of a "script" tag recognition.

### ISSUE THREAD

**Issue by qwemaze** [atom/language-html#113]
![incorrect](http://i.imgur.com/OhmwXQR.png)
![correct](http://i.imgur.com/pVltpKh.png)
So as you can see "type" on newline does not applied on tag contents.

Atom v1.6.2.
Reproduces in safe mode.

**Comment by 50Wliu** [comment]
This is unfixable due to line-based matching.  Sorry about that.
