### ISSUE TITLE
Pre-tag autocomplete probably shouldn't expand

### ISSUE THREAD

**Issue by dchacke** [atom/language-html#115]
Since it displays pre-formatted text, it may be more useful to autocomplete the pre-tag without extra lines or indentation.

**Reproduction Steps:**
1. Open HTML file and be sure to be in HTML syntax mode
2. Type `pre`
3. Hit tab

**Expected result:**

``` html
<pre></pre>
```

**Observed result:**

``` html
<pre>

</pre>
```

**Screenshots and GIFs**

![pre tag autocomplete good and bad](https://cloud.githubusercontent.com/assets/2866749/14799653/7ba2adcc-0af2-11e6-9e7a-af9a6440d113.png)

**Atom version:** 1.7.2
**OS and version:** OS X El Capitan version 10.11.4

**Installed packages:**

``` shell
├── atom-typescript@7.16.0
├── cucumber@0.5.0
└── linter@1.11.3

└── (empty)
```

**Additional information:**
- Problem can be reproduced in safe mode: Yes
- Problem started happening recently, didn't happen in an older version of Atom: No
- Problem can be reliably reproduced, doesn't happen randomly: Yes
- Problem happens with all files and projects, not only some files or projects: Yes, in HTML syntax mode

**Explanation**

When I type `pre` and hit tab, it's autocompleted to:

``` html
<pre>

</pre>
```

So far so good. I think this makes for virtually all other tabs, but perhaps due to this particular tabs nature, it shouldn't expand.

What I mean is that I may want to be able to type `pre` and it's then autocompleted to

``` html
<pre></pre>
```

with the cursor then waiting right in the middle between the opening and closing tag. I find myself removing the whitespace in between almost every time, since I use it predominantly to be populated by a variable's value through some template engine (such as Angular's double curlies). This is especially useful in the middle of the HTML page where there's five levels of indentation, and I wouldn't want that indentation to affect my pre-formatted output.

Like I said, I think the auto-expansion over multiple lines makes perfect sense for pretty much all other tags, but perhaps for this one, staying in one line would be more beneficial.

**Comment by dchacke** [comment]
By the way, I thought I'd mention that I just remembered that tags like `strong` and `em` currently exhibit the desired behavior for the `pre` tag.

**Comment by Shea53** [comment]
I'm a beginner but am having the same sort of problem with `<p>` tags.

Right now they autocomplete to 
```
<p>

</p>
```
rather than 

`<p></p>`

I found this thread that I think solves this problem with snippets: https://github.com/atom/language-html/issues/100 ?
BUT I'm too much of a beginner to implement the solution.. so if someone could explain it in noob terms or tell me how to add this snippet I'd be very happy. Thanks!

**Comment by chharvey** [comment]
related: https://github.com/mattberkowitz/autoclose-html/issues/81

**Comment by esdoppio** [comment]
Sorry for the noise.

@Shea53 http://flight-manual.atom.io/using-atom/sections/snippets/

**Comment by esdoppio** [comment]
A `ipre` (inline pre) expands into `<pre></pre>`.

@dchacke this works for you?

**Comment by dchacke** [comment]
@esdoppio That doesn't work for me.

But I don't think this should be an extra tag. I don't think anybody needs the `pre` tag to expand, so ideally, the `pre` tag's behavior would change instead of adding a new one.

**Comment by chharvey** [comment]
@dchacke agreed. I think the same behavior should also apply to all elements who can only contain **phrasing content** such as `p`,  `h1`–`h6`, `legend`, `option`, etc., as well as phrasing elements themselves (`em`, `strong`, etc.). In other words, only expand the elements who may contain (non-phrasing) **flow content**.

**Comment by esdoppio** [comment]
@dchacke Agreed, actually I had the exact same frustration, so I just overrode it in my own snippets.

**Comment by esdoppio** [comment]
This is much easier to type with `<pre></pre>` as starting point:

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title></title>
</head>
<body>
  <pre><code>body {
  color: red;
}<code></pre>
  <p>ASSIST</p>
  <pre>   Valenz Senher, rei dels Aragones
a qi prez es honors tut iorn enansa,
remembre vus, Senher, del Rei franzes
qe vus venc a vezer e laiset Fransa
   Ab dos sos fillz es ab aqel d'Artes;
hanc no fes colp d'espaza ni de lansa
e mainz baros menet de lur paes:
jorn de lur vida said n'auran menbransa.</pre>
  <p>ASSIST</p>
</body>
</html>
```
