### ISSUE TITLE
'&&' in script fragments incorrectly marked as an error

### ISSUE THREAD

**Issue by z0u** [atom/language-html#116]
I'm using AngularJS (1.4), which requires that I have JavaScript-like expressions in HTML attributes. The problem is that `&` and `&&` in expressions such as `ng-if="!edit.model && !model.length"` are marked as an error and highlighted red:

![image](https://cloud.githubusercontent.com/assets/1408875/15167561/3893c944-176d-11e6-831b-3f8d1d2b9b4c.png)

I think this syntax should be considered valid HTML, because it's not an [ambiguous ampersand](https://www.w3.org/TR/html5/syntax.html#syntax-ambiguous-ampersand).

**Comment by 50Wliu** [comment]
This was fixed by #160.
![unambiguous-ampersand](https://user-images.githubusercontent.com/2766036/30661339-f40da696-9e43-11e7-8316-b52c16de9169.png)
