### ISSUE TITLE
Testing and changing

### ISSUE THREAD

**Issue by ptraceur** [atom/language-html#117]
Hi,
I want to test some modifications on this package. On my Mac, where can I find this folder?
I've looking in `~/.packages/` and `Applications/Atom/Contents/` but couldn't find it.

I want to extend tags functionality. Like different colors for different tags, for example `img` as yellow and `a` as red. To do this, I wanted to test it in the original file.

Thanks.

**Comment by 50Wliu** [comment]
[We're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.

To answer your question though, execute `apm develop language-html [<directory>]` and then start Atom using `atom --dev` to test out your local changes.  The default directory is `~/github/<package-name>`.
