### ISSUE TITLE
Annoying "/>" instead of "/" in HTML

### ISSUE THREAD

**Issue by Vidanox** [atom/language-html#125]
The problem is, when I press "/" button, atom automatically puts "/>"
This is really annoying, especially when I want to type file's direction or "type" attribute in the link tag.
Does anyone know how to turn this feature off?

Also, sorry for the title, I didn't know how to call this issue...

**Comment by esdoppio** [comment]
Can you elaborate on under what circumstances when you input `/` it will become `/>`? And which version of Atom are you on? And can you tell us the packages you have installed that may be related to this?

**Comment by Vidanox** [comment]
Alright, I've found the cause of this issue... It was autoclose package...
