### ISSUE TITLE
double hyphens inside a comment block highlight incorrectly as an error

### ISSUE THREAD

**Issue by albell** [atom/language-html#126]
![double-hyphens-in html-comments](https://cloud.githubusercontent.com/assets/1142025/17256017/78bf52cc-5570-11e6-9f22-ee46bfc31dc7.png)

**Comment by esdoppio** [comment]
In the [LS](https://developers.whatwg.org/syntax.html#comments),

> the comment may have text, with the additional restriction that the text must not start with … nor contain two consecutive U+002D HYPHEN-MINUS characters (--) …

😉
