### ISSUE TITLE
[Improvement request] Add "text/ractive" in begin (html.cson)

### ISSUE THREAD

**Issue by rognoni** [atom/language-html#132]
For my project I'm using **Ractive**:

> Ractive is 99% backwards-compatible with Mustache, but adds several additional features.

http://docs.ractivejs.org/latest/mustaches#extensions

for example:

``` html
<script id='page-tpl' type='text/ractive'>
  <div class='container is-fluid'>
    <div class='columns'>
      <div class='column'>
        <Navigation/>
      </div>
    </div>
    <div class='columns'>
      <div class='column is-3'>
        <Sidebar/>
      </div>
      <div class='column'>
        <div id='component'>TODO...</div>
      </div>
    </div>
  </div>
</script>
```

Can you add the **Ractive** regex please, similar to `x-handlebars`:

``` cson
'begin': '(?:^\\s+)?(<)((?i:script))\\b(?=[^>]*\\btype\\s*=\\s*[\'"]?text/(x-handlebars|(x-(handlebars-)?|ng-)?template|html)[\'"]?)(?![^>]*/>)'
```

https://github.com/atom/language-html/blob/master/grammars/html.cson

Probably this feature is related to https://github.com/atom/language-mustache/issues/15

**Comment by 50Wliu** [comment]
Closed by #171.
