### ISSUE TITLE
Inline CSS within HTML (on HTML syntax) should be highlighted

### ISSUE THREAD

**Issue by revelt** [atom/language-html#135]
The issue #3 indirectly mentioned this issue, but was closed few years ago.
Currently, Atom HTML syntax doesn't highlight inline CSS. Here's `Atom Dark` UI+Syntax:

![atom_html_syntax](https://cloud.githubusercontent.com/assets/8344688/18914033/3ba0e93a-8583-11e6-934f-333370247a67.png)

**Comment by nichtchris** [comment]
Is there any news on this? I use the `One Dark` theme (and `One Dark UI`) and it looks like this:

![inline-css](https://cloud.githubusercontent.com/assets/18736095/22734646/b3f6dc06-edf6-11e6-8754-70b2399d0c27.PNG)

I've tried several syntax themes (see screenshot below) but there is none that highlights inline CSS. All themes show the content of `style=""` in one colour like @revelt mentioned.

![themes](https://cloud.githubusercontent.com/assets/18736095/22734649/b5b7aed0-edf6-11e6-8eda-285e394ac18f.PNG)

This would be a really great improvement :)

**Comment by 50Wliu** [comment]
Yes, this is because it hasn't been implemented yet.  There's a few things that need to be knocked out of the way first before it'll become feasible.

**Comment by nichtchris** [comment]
@50Wliu 
Alright thanks for the heads up! Looking forward to this :thumbsup:

**Comment by 50Wliu** [comment]
![html-style-attribute-css](https://user-images.githubusercontent.com/2766036/30523884-f12f2e56-9be9-11e7-87be-9a635067ce9c.png)
PR coming soon :wink:

**Comment by revelt** [comment]
Exciting!!! It's like Christmas present... I code email mainly and nearly all CSS I actually type is exclusively inline... This will reduce the cognitive load greatly.. Looking forward to that..

**Comment by 50Wliu** [comment]
Sorry for the delay, I just merged the PR.  This _should_ be going out in Atom 1.25 unless there are delays.
