### ISSUE TITLE
PHP syntax support within HTML syntax

### ISSUE THREAD

**Issue by michaelGregoire** [atom/language-html#14]
Most editors have PHP syntax/language support within HTML files, due to the commonality of having PHP within HTML templates. Currently, Atom does not. I hope that this can be rectified. Not having it is a deal breaker for me.

Atom HTML syntax highlighting:
![atom-html-syntax](https://f.cloud.github.com/assets/1930152/2412958/d3d5291a-aad8-11e3-909b-0e58de2128ad.jpg)

Sublime Text HTML syntax highlighting:
![sublime-html-syntax](https://f.cloud.github.com/assets/1930152/2412968/eaa18a26-aad8-11e3-99cf-12e78b609cf6.jpg)

**Comment by biacz** [comment]
This is not 100% correct.
I am a totally new Atom user and this is whats happening for me (index.php).
![image](https://cloud.githubusercontent.com/assets/7847491/6549964/694e98ea-c61d-11e4-836b-18fdcd7131bc.png)

Any idea how to fix that? Its really annoying.

**Comment by Shaqattack118** [comment]
How do you fix this?

**Comment by 50Wliu** [comment]
<kbd>Ctrl+Shift+L</kbd> (or <kbd>Cmd+Shift+L</kbd>) and switch the language to PHP.

**Comment by shudson250** [comment]
thanks @50Wliu that solved it for me. Not sure if it will stick though

**Comment by arthurbragaa** [comment]
Thanks @50Wliu.

**Comment by nhoxx** [comment]
Thanks a lot @50Wliu !

**Comment by UncleGena** [comment]
`Ctrl+Shift+L`  will not save, and you don't want press it on each of 2345 files in your project.
my solution:

1. download [file-types](https://atom.io/packages/file-types) 
2. go to Edit -> Config file
3. wright 
![screenshot from 2017-01-04 10 12 37](https://cloud.githubusercontent.com/assets/11743243/21635607/63402f56-d267-11e6-8193-4734cddc8d75.png)

4. press Ctrl+S and restart Atom.

![screenshot from 2017-01-04 10 11 35](https://cloud.githubusercontent.com/assets/11743243/21635590/558b979c-d267-11e6-8c3c-2becc8b49d7a.png)
