### ISSUE TITLE
Single quote in paragraph cause the rest of the file to be highlighted in red

### ISSUE THREAD

**Issue by PatrickJoannisse** [atom/language-html#144]
![atom-language-html-issue](https://cloud.githubusercontent.com/assets/2472370/20239776/c409de32-a8d6-11e6-8760-21478d92c7cd.PNG)

**Comment by 50Wliu** [comment]
The issue appears to be something else: please narrow down your example to the smallest-possible file that will still reproduce this error.

**Comment by PatrickJoannisse** [comment]
The PHP formatting above was causing the issue. 

**Original formatting**

    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>

**Formatting without any issue**

        window.Laravel =
        <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>

The formatting comes from Laravel's template (app.blade.php if you're curious).

**Comment by 50Wliu** [comment]
The PHP issue has been fixed already and should be available in Atom 1.14.0.
