### ISSUE TITLE
Attribute after a newline not highlighted

### ISSUE THREAD

**Issue by m93a** [atom/language-html#157]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The syntax highlighting doesn't work properly if you split a *begin tag* so that an attribute definition appears immediately *after a newline*.

### Steps to Reproduce

A) This is highlighted properly:
```html
<span
  class="foo">
```

B) This isn't highlighted:
```html
<span
class="foo">
```

**Expected behavior:** A

**Actual behavior:** B

**Reproduces how often:** 100%

### Versions

* Atom: 1.15.0 ia32
* Windows 10

**Comment by 50Wliu** [comment]
Fixed by #164.
