### ISSUE TITLE
Angular2 & Atom - Using Question Mark Syntax '?' in HTML causes HTML tag discoloration

### ISSUE THREAD

**Issue by 02harleen** [atom/language-html#163]
Atom does not support in HTML angular2 question mark Syntax '?'. Please tell us how to support question mark Syntax '?' in atom HTML.

**Comment by 50Wliu** [comment]
This would need to be supported by a language package specifically designed for Angular 2.  You can ask on [Discuss, the official Atom and Electron message board](https://discuss.atom.io) or [join the Atom Slack team](http://atom-slack.herokuapp.com/) for more help.  There are a bunch of helpful community members that should be willing to point you in the right direction.
