### ISSUE TITLE
Please improve the addon's features

### ISSUE THREAD

**Issue by Raj2032** [atom/language-html#189]
Sure it is great that there is a support for HTML but the support is so limited. For starters when I type
```
<head>
```
for example, why can't it do this:
```
<head>
    (some space)
</head>
```
Even notepad++ something like this.

**Comment by 50Wliu** [comment]
language-html only provides syntax highlighting and snippets.  You can install packages to add the feature you are asking for, such as https://atom.io/packages/autoclose-html.
