### ISSUE TITLE
let's add missing mso- attribute values to the inline CSS spec

### ISSUE THREAD

**Issue by revelt** [atom/language-html#192]
Currently, some `mso-...` inline CSS attribute values are not recognised. @webtobesocial compiled all the prefixes in a [Gist here](https://gist.github.com/webtobesocial/ac9d052595b406d5a5c1).

In practice, this issue means Outlook proprietary inline CSS attributes, used in email template development currently don't get highlighted correctly, for example:

<img width="508" alt="screen shot 2018-03-23 at 14 39 18" src="https://user-images.githubusercontent.com/8344688/37835404-00b60a60-2ea8-11e8-995a-9b4f0bac124f.png">

In the example above, I'd expect `mso-line-height-rule`'s value to be highlighted same colour as `float`'s.

**Comment by 50Wliu** [comment]
Ah, this should actually be in language-css. @revelt could you please reopen this issue there instead?  Thanks!
