### ISSUE TITLE
Strange tabulation happening after tag is inserted

### ISSUE THREAD

**Issue by revelt** [atom/language-html#196]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

For the record, this doesn't happen in Safe mode, but it's because this package is off.

Indentation jumps from beginning of an empty line straight to line below, to the end of a closing tag:

![tabbing](https://user-images.githubusercontent.com/8344688/39001126-73c72c14-43ed-11e8-9138-47f1518f9439.gif)

If succeeds from second attempt.

### Steps to Reproduce

1. Create and save HTML file.
2. `tr` + tab key
3.  `td`+ tab key
4. split TD tags into separate lines (type ENTER twice), 
5. move cursor into this new middle empty line
6. click tab

**Expected behavior:** [What you expect to happen]

Atom should generate bunch of indentations and move the cursor to the end of them.

**Actual behavior:** [What actually happens]

Atom does not create indentations but jump to the line below, to the end of it.

**Reproduces how often:** 100%

### Versions

Atom    : 1.26.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
OS: High Sierra, 10.13.4 (17E199)

### Additional Information

It succeeds in second attempt.

**Comment by 50Wliu** [comment]
> For the record, this doesn't happen in Safe mode, but it's because this package is off.

language-html is a default package and as such is enabled in Safe mode.  Are you sure it isn't another package that is interfering with the snippet expansion?
