### ISSUE TITLE
HTML style tags do not have syntax highlighting enabled

### ISSUE THREAD

**Issue by matt3224** [atom/language-html#216]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

HTML style tag syntax highlighting does not work

### Steps to Reproduce

1. Create html file 
2. Write a style tag with a css declaration

```html
<style>
    .color {
        color: red;
    }
</style>
````

**Expected behaviour:**
Styles would be syntax highlighted

**Actual behavior:**
Style tag content is not syntax highlighted 

**Reproduces how often:**
100%

### Versions

macOS : 10.14
Atom    : 1.31.2
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.1
npm  6.2.0
node 8.9.3 x64
atom 1.31.2
python 2.7.10
git 2.17.1

Originally posted here: [#18212](https://github.com/atom/atom/issues/18212)

**Comment by Arcanemagus** [comment]
Looks like this is a regression in the Tree-sitter grammar. You can work around this for now by disabling Tree-sitter parsers in the settings @matt3224.

Tree-sitter:
![image](https://user-images.githubusercontent.com/427137/46682402-4a826480-cba2-11e8-960c-2a632a9bf6e2.png)

TextMate:
![image](https://user-images.githubusercontent.com/427137/46682364-33dc0d80-cba2-11e8-8ce9-0660fbaea929.png)

Thanks for the report!

**Comment by maxbrunsfeld** [comment]
This is fixed.

**Comment by Mosrod** [comment]
I had this same issue, which was fixed by disabling the package Pigments, which changed TextMate to Tree-sitter.
