### ISSUE TITLE
Toggle individual lines within comment blocks in inline CSS

### ISSUE THREAD

**Issue by mcandre** [atom/language-html#225]
When editing inline CSS, it is often helpful to quickly toggle CSS attributes on a line-by-line basis.

For example, rather than declaring `/* ... */` for the whole cursor selection, insert these tokens once per line.

And, when the user instructs Atom to toggle comments back off within a multiline comment block, then insert a comment term (`*/` just before that line, and insert a start comment (`/*`) term just after that line, when necessary.

**Comment by rsese** [comment]
Thanks for the suggestion!  Though I can see how useful this could be for folks, changing or extending the behavior of how comment toggling works at this point isn't something the team would prioritize so we'll go ahead and close this.  The functionality you describe is something that would probably be better as a community package too; there's a number of community packages that provide different commenting functionality already so there might even be something out there that does what you want (I didn't find one after a quick search though).

But thank you again for the ideas!
