### ISSUE TITLE
Different Parsing between "HTML" and "Auto Detect"

### ISSUE THREAD

**Issue by PlaidPhantom** [atom/language-html#226]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I get different parsing behavior between when I open a file and select the "Auto Detect" language option and when I specifically select "HTML".

### Steps to Reproduce

1. Open an HTML file
2. open the language selector and select "Auto Detect"
3. View the parsed classes in the Inspector
4. open the language selector and select "HTML"
5. see that the classes for tokens has changed

**Expected behavior:** [What you expect to happen]

The parsing is the same, whether auto-detected or manually selected.

**Actual behavior:** [What actually happens]

The parsing is different.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Versions

OS: Ubuntu 18.04.02

I suspect I am having the same issue on Mac OS X on my work computer. I can check tomorrow if it is helpful.

```
$ atom --version
Atom    : 1.36.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
```
$ apm --version
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.36.1
python 2.7.15rc1
git 2.17.1
```

### Additional Information

When I disable Tree Sitter parsers, this problem goes away.  It seems like when I pick "HTML" it is using Tree-Sitter parsing  but when I auto-detect I get the old parsing.

**Comment by rsese** [comment]
Thanks for the report!   I can reproduce what you describe with 1.36.1 on macOS 10.12.6 -  this is with the cursor on the `<h1>`, the top 2 messages are after your step (2) and the last 2 messages are after your step (4):

![html-grammar-selector](https://user-images.githubusercontent.com/734194/57167788-a7ef3480-6dc4-11e9-9b35-85a34c02dfa9.png)

I think this is related to https://github.com/atom/atom/issues/17029 yeah @Aerijo?

**Comment by Aerijo** [comment]
@rsese yes

**Comment by rsese** [comment]
Great thanks @Aerijo - so would this then be fixed by [your PR](https://github.com/atom/atom/pull/18738)?  Just wondering if we should add a "closes" in there...
