### ISSUE TITLE
no detection to jinja2 code in html files

### ISSUE THREAD

**Issue by hefayed** [atom/language-html#233]
Hi,

i am not sure this is expected behavior or not , when i have jinja2 code in a .html file it is not recognized with different color. To be fair i am not sure this is the right place to ask this question or not , attached is a sample file. One file is .html the other is .html.j2 to show the syntax. the problem with the second one which is .html.j2 linter doesnt work and i am not sure where is the issue is.

.html file
![bad](https://user-images.githubusercontent.com/13040034/65846281-1abbf780-e2f2-11e9-8fa1-412f1b20f778.png)

the file is the .html.j2
![good](https://user-images.githubusercontent.com/13040034/65846282-1abbf780-e2f2-11e9-9ee0-bb862b9ec995.png)

Regards,
Hesham

**Comment by Arcanemagus** [comment]
It sounds like you have a "jinja2" language installed that recognizes `.html.j2` files, and want to have regular `.html` files to _also_ be recognized as "jinja2" files, is that correct?

If that's the case you can customize how Atom is recognizing the follows by following this part of the Flight Manual:
[Customizing Language Recognition](https://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-language-recognition)

**Comment by hefayed** [comment]
it worked, thanks allot
