### ISSUE TITLE
Highlight matching element tag

### ISSUE THREAD

**Issue by rtorr** [atom/language-html#24]
Most editors that support HTML will match the open and closing tags with the cursor is touching one or the other.

Examples:
Showing matching div (tag underlined)
![screenshot 2014-05-08 21 31 31](https://cloud.githubusercontent.com/assets/297045/2924392/0b446dee-d733-11e3-83e0-8bcf7eb4699e.png)

Showing matching p (tag underlined)
![screenshot 2014-05-08 21 34 08](https://cloud.githubusercontent.com/assets/297045/2924397/30c5fb78-d733-11e3-92d8-f28a72b48447.png)

**Comment by Saul-BT** [comment]
Highlight the label of the corresponding element, I think it is difficult to find the end of the label with the label simply underlined, you should put options to choose, such as that the label of the element has a border of a certain color.

Thanks

**Comment by hasnainbaloch** [comment]
ctrl+d it works

**Comment by hasnainbaloch** [comment]
ctrl + m
