### ISSUE TITLE
Script tag classes change depending on indent

### ISSUE THREAD

**Issue by thomaslindstrom** [atom/language-html#25]
``` html
<script type="text/javascript" src="script.js"></script>
```

is recognized as `text html basic` with a child `meta tag any html`, whilst

``` html
    <script type="text/javascript" src="script.js"></script>
```

is recognized as `text html basic` with a child `source js embedded html`.
I don't know which is intended, but the fact that it's changing depending on its indent is weird, no?

**Comment by mnquintana** [comment]
:+1: I just ran into this. If a script tag is indented, and you Toggle Line Comments (<kbd>Ctrl/Cmd+/</kbd>), you will get a JS single-line comment (e.g. `//`) instead of an HTML comment (e.g. `<!-- -->`). You do get an HTML comment however if the script tag is unindented.

**Comment by mixmatch** [comment]
https://github.com/atom/language-html/blob/94e850dc4ab848baac1f413e4cb864864e1c24f8/grammars/html.cson#L216
