### ISSUE TITLE
new keyword

### ISSUE THREAD

**Issue by samstr** [atom/language-html#29]
I feel like "new homepage" shouldn't be highlighted.

![screen shot 2014-05-27 at 11 29 13](https://cloud.githubusercontent.com/assets/428626/3095893/28f68d92-e5cd-11e3-9643-d5e50e09461a.png)

Probably something to do with having this stuff inside a ```script``` element also.

**Comment by kevinsawicki** [comment]
Closing this out, I believe this is something that should be handled by the angular package, https://github.com/angular-ui/AngularJS-Atom since it provides syntax highlighting for this type of construct.
