### ISSUE TITLE
Provide option to disable snippets

### ISSUE THREAD

**Issue by valorin** [atom/language-html#40]
There are so many single character snippets provided by this package, and they interfere with normal usage, and even other snippets.

For example, I have a snippet `copy:ia`, but the `a` at the end triggers one of these snippets instead of mine.

**Comment by Fank** [comment]
@valorin i found something like this -> https://github.com/atom/snippets/issues/55

**Comment by mnquintana** [comment]
@valorin That actually sounds like a different issue – it sounds like [atom/snippets](https://github.com/atom/snippets) isn't expanding snippet prefixes properly, since it should be looking at the whole token, not just the ending of it for determining expansion.

**Comment by kevinsawicki** [comment]
Closing this out in favor of https://github.com/atom/snippets/issues/55 which enables support for it for all packages.
