### ISSUE TITLE
Quotes are handled horribly

### ISSUE THREAD

**Issue by Kangaroopower** [atom/language-html#46]
If you have a quote inside a note (  ) the highlighting gets all messed up and starts labeling everything as a string, and same for if you have something inside a tag ( < p > " </ p >  I put spaces in the  p tags to stop them from rendering). It's a problem with single AND double quotes.

**Comment by kevinsawicki** [comment]
> @Kangaroopower can you include the entire text of the file in that screenshot?

If you could provide this it would make it much easier to debug and see what is going wrong, thanks.

**Comment by Kangaroopower** [comment]
oops just saw this. Weirdly enough, I don't see the issue any more. It might have just been a one time thing.

**Comment by kevinsawicki** [comment]
Thanks for letting us know, closing this out, please comment if you see it again.
