### ISSUE TITLE
Define custom file types in the preferences

### ISSUE THREAD

**Issue by itadakimas** [atom/language-html#49]
Hi !

Sometimes when you use files with custom extensions (such as .hbs), the language-html doesn't recognize it. Until now, I managed to add the hbs file type in the sources. But every time I update the package, my modifications are undone.

Can you add the possibility to define custom file types in the settings panel ?

Thank you.

**Comment by lee-dohm** [comment]
This is essentially a duplicate of atom/atom#1718. This is a problem for all language packages, not just language-html. Please subscribe to the above issue for updates.

Thanks for reporting!
