### ISSUE TITLE
default charset attribute for script tag seems odd

### ISSUE THREAD

**Issue by doginthehat** [atom/language-html#53]
The default auto-expand attribute for a script tag is `charset="utf-8"`

	<script charset="utf-8">
		
	</script>

I don't think i've ever had to use this attribute on a script tag. 

`type="text/javascript"` would seem like a better choice.

I'm on `Atom 0.190.0` & `language-html 0.31.0`

**Comment by thomasjo** [comment]
By default (at least in Chromium and other modern browsers) when `type` is absent, `text/javascript` is assumed, so these days it should no longer be specified. The charset/encoding however, is *not* assumed to be UTF-8 by default, so the current snippet makes perfect sense, at least if you're not using UTF-8 on the root node level.

**Comment by doginthehat** [comment]
@thomasjo 

I'm just speaking from experience – I never had to use the charset attribute as I usually utf8 all the things and since it defaults to the document's charset, it works fine. I find it more common to have to set the type, to `text/template` or `text/jsx` recently.

To be technically correct, if you're offering the `charset` attribute, you should also offer the `src` attribute as well as they only make sense together ([according to the specs](http://www.w3.org/TR/html-markup/script.html): Element script must not have attribute charset unless attribute src is also specified.)

**Comment by thomasjo** [comment]
Good points @doginthehat. I [opened a PR](https://github.com/atom/language-html/pull/54) that tries to improve the behavior according to your description. It'd be great if you could check whether this resolves your issue in a satisfactory manner.
