### ISSUE TITLE
First lines <?php got invalid

### ISSUE THREAD

**Issue by suisho** [atom/language-html#55]
Hi.

I use html on php source code.
And I got breaking syntax highlight when `<?php` tag first line.

![php](https://cloud.githubusercontent.com/assets/1523007/7153044/32295608-e381-11e4-9038-ce3122acd0e5.png)

Inspector source is this

```html
<span class="text html php">
  <span class="invalid illegal bad-angle-bracket html">&lt;</span>?php
</span>
```

And when I solve this error when toggle disable and enable language-html package.

**Comment by izuzak** [comment]
I'm having trouble reproducing this, @suisho. Can you clarify which version of Atom you're using? Also, can you provide exact steps to reproduce? Assume I started Atom and have no tabs open yet -- which steps do I need to make to reproduce this? Also, can you reproduce this in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by suisho** [comment]
I use atom 0.190.0 and I got this issue without steps.

But when I try safe mode, I'm not got this issue.
I check other modules.
thank you.

**Comment by suisho** [comment]
Oh, I found conflict package.
https://atom.io/packages/language-vue-component 

Thank you.
