### ISSUE TITLE
Autocompleting of html tags with dashes fails

### ISSUE THREAD

**Issue by KrisSiegel** [atom/language-html#58]
If you have a structure like the following:

```
<div>
    <my-component>
</div>
```

When you attempt to type ```</``` after the ```<my-component>``` tag it will autocomplete to close it as a ```</div>```.

Are autocomplete rules part of this package or another package? Sorry if this is the wrong repository but this issue has been driving me nuts :)

**Comment by 50Wliu** [comment]
I think you might have an external package that's autocompleting it wrong - Atom doesn't automatically close HTML tags for you yet.

To answer your question though: autocomplete rules are a part of both [autocomplete-plus](https://github.com/atom/autocomplete-plus) (provides the basis for more selective autocompletion) and [autocomplete-html](https://github.com/atom/autocomplete-html) (provides autocomplete specifically for HTML files).  This package only handles highlighting, auto-indentation, and other settings related to HTML.

**Comment by KrisSiegel** [comment]
Ah thanks. It's been a long time since I've checked this. I just double checked and at the moment it would seem I no longer have autocomplete for custom elements (so instead of doing the wrong thing it does nothing at all). I'll look into those repos to see if I can post something better there as I think this can be a little better :)
