### ISSUE TITLE
Single quote in html comment section should be ignored

### ISSUE THREAD

**Issue by brennanMKE** [atom/language-html#59]
I just generated a sample project using using the Ionic Framework and has an html file which has a line of text enclosed as a comment. You can see from the screenshot that it colors the code incorrectly as it thinks the single quote, uses as an apostrophe, is not handled properly.

I am running version 0.188.0 of the Atom editor.

To recreate it simply install the Ionic framework and generate a project. Open the html file index.html in sample/www. It shows the problem at line 21. See screenshot below.

![bug](https://cloud.githubusercontent.com/assets/277419/7461459/58693152-f25f-11e4-9b57-3650fd03a2c4.png)

**Comment by mnquintana** [comment]
You're running an old version of Atom - can you try updating to the latest version (0.196.0) and see if you still experience this issue?

**Comment by brennanMKE** [comment]
It appears to still be an issue in 0.196.0. I also updated all plugins.

![atom bug](https://cloud.githubusercontent.com/assets/277419/7479163/a37ea48c-f314-11e4-83dc-d354beab1559.png)

**Comment by mnquintana** [comment]
I can't reproduce this in Atom 0.196.0 on OS X 10.10.3:

![image](https://cloud.githubusercontent.com/assets/823545/7479823/30d7d6b0-f332-11e4-9f07-14627e10b038.png)

I suspect that a package is causing this. Does this happen in safe mode (`atom --safe`)? What language grammar do you have active?

**Comment by brennanMKE** [comment]
I'll have to check when I am back at work in the morning. I do not have this issue on my computer at home. How can I get a list of installed packages so that I can provide a list to compare my work and home computers?

**Comment by mnquintana** [comment]
@brennanMKE You can run `apm list --installed` to get a list of installed packages.

**Comment by brennanMKE** [comment]
Below is the list on the affected computer.

```
> apm list --installed
/Users/brennan/.atom/packages (18)
├── .bin
├── angularjs@0.2.0
├── atom-beautify@0.27.0
├── atom-jsx-transform@0.1.0
├── atom-typescript@4.1.5
├── autocomplete-clang@0.6.9
├── autocomplete-css@0.6.0
├── autocomplete-html@0.6.0
├── autocomplete-plus@2.12.1
├── autocomplete-snippets@1.4.0
├── javascript-snippets@1.0.0
├── jshint@1.3.5
├── language-javascript-jsx@0.3.1
├── language-jsx@0.1.4
├── linter@0.12.1
├── node-debugger@0.2.3
├── project-manager@1.15.5
└── react@0.11.8
```

**Comment by mnquintana** [comment]
Can you try checking in safe mode? (`atom --safe`)

**Comment by brennanMKE** [comment]
It looks like correct with `atom--safe`. It must be one of those extensions. Is there a way to disable plugins from the command-line? I could disable them one by one until it does not happen to narrow it down.

**Comment by mnquintana** [comment]
There actually isn't a way to disable packages from the command line right now, but you can disable packages in Atom in Preferences > Packages.

**Comment by brennanMKE** [comment]
It appears that this is the package which is causing the problem. I can disable it, restart Atom and it does not happen. Then if I enable the package and restart the problem is back.

https://github.com/subtlegradient/language-javascript-jsx

**Comment by brennanMKE** [comment]
It appears that this issue was reported in March.

https://github.com/subtleGradient/language-javascript-jsx/issues/2

**Comment by mnquintana** [comment]
@brennanMKE Yup, confirmed, I can reproduce this with that package installed - thanks for the update!

That package doesn't seem maintained anymore - maybe you'll have better luck with [this one?](https://atom.io/packages/language-jsx) (Note: I haven't tested it)

**Comment by brennanMKE** [comment]
Thanks, I will just wait till Nuclide is out before I dig into jsx. For now I am learning TypeScript with Visual Studio Code. It is great to see all of these Atom editors coming out.
