### ISSUE TITLE
PHP Short-Tag highlighting (0.198.0)

### ISSUE THREAD

**Issue by jccrofty30** [atom/language-html#60]
Since updating to version 0.198.0, short-tag highlighting seems to be bugged.

If there are no spaces between an element and a short-tag opening there is no syntax highlighting for the rest of the line (i.e. `<strong><?=date('l', strtotime($day))?></strong>`).

Placing a space before the opening tag corrects the issue (i.e. `<strong> <?=date('l', strtotime($day))?></strong>`).

Also, as soon as a space is encountered outside of the short-tag, highlighting resumes (i.e. `<strong<?=date('l', strtotime($day))?> </strong>`).

It is the same issue anywhere there is a short-tag.

**Comment by AlexanderOMara** [comment]
+1 Here are the details [I just reported on the main Atom repo](https://github.com/atom/atom/issues/6709).

I just updated to Atom version 0.198.0 and I've noticed an issue I didn't have yesterday.

The PHP syntax highlighting breaks on the following code:

```php
<?php
$highlighted = true;
?><p>test</p><?php
$highlighted = false;
```
![without space](https://i.imgur.com/hFs0mpi.png)

I've narrowed it down to this sequence of characters that is tripping it up.

    ><?php

Plus the short-hand variation.

    ><?

If I change the code to have a space in between it works.

```php
<?php
$highlighted = true;
?><p>test</p> <?php
$highlighted = false;
```

![with space](https://i.imgur.com/92QlATM.png)

I'm guessing this is related to the recent PHP-related changes listed in the change log.
