### ISSUE TITLE
Don't match <!doctype html> in .html.erb files

### ISSUE THREAD

**Issue by jazzpi** [atom/language-html#68]
Currently, my `.html.erb` files don't get correctly detected as `HTML (Ruby - ERB)` or `HTML (Rails)` but as plain `HTML` - I assume because of the `'firstLineMatch'` line in the grammar file. Would it be possible to not match `<!doctype html>` as a first line if the file extension is `.html.erb`?

**Comment by izuzak** [comment]
Thanks for the feedback. I think this is related to https://github.com/atom/atom/issues/2734 -- could you add a comment there please?

**Comment by jazzpi** [comment]
Oh, yes, I didn't see that issue, sorry :neutral_face:
