### ISSUE TITLE
snippets

### ISSUE THREAD

**Issue by briankoudijs** [atom/language-html#74]
It's impossible for me to write HTML snippets. Tried to configure some but without luck. Tried using: .text.html.basic also tried a snippet for CSS using .source.css and this works. Any solutions for that?

**Comment by kevinsawicki** [comment]
This worked for me in my `~/.atom/snippets.cson` file:

```coffee
'.text.html':
  'hi':
    'prefix': 'h'
    'body': 'hi there'
```

You can see also the scopes used for the built-in snippets [here](https://github.com/atom/language-html/blob/fdecd5b907eedf83fbc2b337437717953a9d7765/snippets/language-html.cson#L1).


Closing this out, please comment if you still have issues.
