### ISSUE TITLE
feature request: option for single-line tags (no newline)

### ISSUE THREAD

**Issue by dwhieb** [atom/language-html#77]
It would be great to have an option for tags to be autocompleted without newlines. So instead of tab producing this:
```
<p>
    [cursor]
</p>
```
it would instead produce this:
```
<p>[cursor]</p>

**Comment by kritsky** [comment]
yeah, this would be great!

**Comment by heinst** [comment]
@dwhieb you probably want to create the issue on this repo: https://github.com/atom/autocomplete-html

**Comment by dwhieb** [comment]
@heinst thanks!

**Comment by dwhieb** [comment]
moving issue to the autocomplete-html repo
