### ISSUE TITLE
No HTML syntax highlighting with large amounts of script content.

### ISSUE THREAD

**Issue by dagrooms52** [atom/language-html#78]
I have an HTML file that consists of about 50% Javascript. While Atom recognizes the HTML file, after the script tags there is no HTML syntax highlighting; however, it highlights the Javascript portion of the file perfectly. All HTML after this point is one color, with a gray color for strings (between "&"). I have the HTML language package installed and enabled.

**Comment by 50Wliu** [comment]
Is there any chance you can share the file in question?
If not, can you please try to create a minimal repro case?

**Comment by dagrooms52** [comment]
I can't, it's owned by the company I work for and probably shouldn't be released in a public forum.
Imagine a simple html file:

    <html>
    <head>
    <script>
        function doSomething() {
            // Sees the javascript just fine
        }
    </script>
    
    </head>
    <body>
        <h1>Some text</h1>
    </body>
    </html>

**Comment by 50Wliu** [comment]
I can't seem to reproduce this - can you please see if it still happens in safe mode (`atom --safe`)?

**Comment by dagrooms52** [comment]
For some reason the editor caused a hanging quotation mark to randomly appear that isn't present in other text editors I've used. In any case, I found the problem. Thanks for your help.
