### ISSUE TITLE
HTML/Angular syntax coloring not complete or consistent

### ISSUE THREAD

**Issue by smlombardi** [atom/language-html#79]
I love that there is now an html/angular syntax type.

However, I I am using it and trying to integrate it into my themes, I noticed it only worked in SOME places.  Not sure why, but I hope it can be expanded and made consistent:

![angular syntax](https://cloud.githubusercontent.com/assets/835148/8440944/768f36ca-1f43-11e5-85b6-711aa2526ea9.png)

**Comment by kevinsawicki** [comment]
Angular syntax highlighting is provided by https://github.com/angular-ui/AngularJS-Atom

If this is still an issue, you should open it there, closing it out here.
