### ISSUE TITLE
Embedded scripts handled poorly

### ISSUE THREAD

**Issue by chbk** [atom/language-html#82]
Scopes for embedded scripts start too soon and end too late, and syntax highlighting gets messed up:

![htmlbug](https://cloud.githubusercontent.com/assets/7478535/9546055/b0ba6d72-4d8f-11e5-8fc0-bfa7180cd6ef.png)

This is how it should be scoped IMO:

![htmlsource](https://cloud.githubusercontent.com/assets/7478535/9546056/b2fd3178-4d8f-11e5-8adb-8c5c133758da.png)

**Comment by alexchandel** [comment]
This is especially the case for non-JS script tags, as in #88.

**Comment by Stanzilla** [comment]
So basically a followup for @benogle 's change in https://github.com/atom/language-html/pull/80

**Comment by 50Wliu** [comment]
I believe I've found a fix for this in #90 (by using patterns in `beginCapture` for tag stuff instead of in `captures`).
