### ISSUE TITLE
Interest in HTML Entities Autocomplete

### ISSUE THREAD

**Issue by cakebake** [atom/language-html#87]
Should this package automatically suggest HTML Entities like `&nbsp;`, `&amp;`, `&uuml;`, ..., or would that be the task of other packages? I currently still found none and would offer me to start a merge request for the snippets here.

**Comment by mnquintana** [comment]
Great idea! I think in this case it would make the most sense to implement in https://github.com/atom/autocomplete-html (since those entities aren't really snippets) - would you mind opening an issue there?

**Comment by cakebake** [comment]
Ref. atom/autocomplete-html#14

**Comment by jeancroy** [comment]
Ok then the list of language related keyword for autocomplete would be in
https://github.com/atom/language-html/blob/master/settings/language-html.cson

The completions setting is not used right now but I believe it can be done like for php
https://github.com/atom/language-php/blob/master/settings/language-php.cson#L5
