### ISSUE TITLE
Auto-sync renaming of tag pair

### ISSUE THREAD

**Issue by donaldpipowitch** [atom/language-html#92]
It would be nice, if Atom would sync the renaming of an opening tag with the closing tag like WebStorm. E.g. you have `<div></div>` and rewrite the first  `<div>` to  `<p>` the result should be  `<p></p>`.

**Comment by MaximSokolov** [comment]
You can do it via Emmet package: emmetio/emmet-atom#154

**Comment by donaldpipowitch** [comment]
But I need to trigger that with `CTRL+SHIFT+'` right? It doesn't update automatically.

**Comment by 50Wliu** [comment]
Closing in favor of atom/bracket-matcher#63, especially since this package only handles highlighting and scoped settings related to HTML.

**Comment by donaldpipowitch** [comment]
Thanks.
