### ISSUE TITLE
feature request: jade-style input autocompletion

### ISSUE THREAD

**Issue by smnbbrv** [atom/language-html#99]
I really like the autocompletion which allows you to write everything directly, fast and short. The example of one I really like I first found on Webstorm IDE, but it appears that even jsfiddle has a similar one.

The idea is pretty simple. Using jade-like notation try to type on https://jsfiddle.net/ in HTML section:

```html
div - then press Tab - <div id="abc"></div> generated
div#abc - then press Tab - <div id="abc"></div> generated
div#abc.hello - then press Tab - <div id="abc" class="hello"></div> generated, etc.
```

This is a really cool feature, you forget about symbols <, ', " and > and you type only valuable things, like div.

But what I really like on the same jsfiddle is that you can autocomplete even not existing tags which feels so good for angular directives!

```html
contact-list - then press Tab - <contact-list></contact-list> generated
```

For me this would be a huge improvement.

Sorry if I posted it to a wrong repository.

**Comment by lee-dohm** [comment]
I think what you're looking for is the [Emmet package](https://atom.io/packages/Emmet). While it provides the feature you're looking for, we have had some issues with it creating problems with keybindings, so you may want to keep that in mind.
